Repository lasp/space_packet_parser, pull requests merged in 2024-10, with the labels that each got.

#95 DOC: Minor updates to documentation
  docs/source/_static/browser-parsing.html
  space_packet_parser/parameters.py
Labels: documentation

#96 Prepare for Release of 5.0.0
  .github/issue_template.md
  .github/pull_request_template.md
  CITATION.cff
  README.md
  docs/source/changelog.md
  pyproject.toml
Labels: release

#101 Fix bug in representing falsy raw value in parsed _Parameters
  CITATION.cff
  docs/source/changelog.md
  pyproject.toml
  space_packet_parser/packets.py
  space_packet_parser/parameters.py
  tests/unit/test_xtcedef.py
Labels: bug

#102 Fix bug in release pipeline prerelease regex
  .github/workflows/release.yml
Labels: bug
