Repository lasp/space_packet_parser, pull requests merged in 2024-09, with the labels that each got.

#26 Add straightforward endianness implementation; accommodate all allowable string encodings
  pylintrc
  space_packet_parser/canonicalized_strings.py
  space_packet_parser/xtcedef.py
  tests/unit/test_xtcedef.py
Labels: enhancement

#61 FIX: Return the raw bytes from a BinaryDataEncoding
  docs/source/changelog.md
  space_packet_parser/xtcedef.py
  tests/integration/test_xtce_based_parsing/test_suda_parsing.py
  tests/unit/test_xtcedef.py
Labels: breaking

#71 DOC: Add in-browser capability
  docs/source/_static/browser-parsing.html
  docs/source/browser-demo.rst
  docs/source/contents.rst
Labels: documentation
